### PR TITLE
Adding fdosani

### PR DESCRIPTION
**Pull request by fdosani**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

I'm one of the maintainers of `datacompy` and would love to be added as a maintainer for the conda-forge package if possible. The latest version of `datacompy` is at 0.7.1, am happy to spend some time to keep this maintained going forward.

### CODE REVIEW

**Comment by fdosani** [comment]
@conda-forge-admin please rerender

**Comment by fdosani** [comment]
@conda-forge-admin, please rerender

**Comment by fdosani** [comment]
@conda-forge-admin, please restart ci

**Comment by gforsyth** [comment]
Hey @conda-forge/help-python -- is anyone available who can merge this in to add @fdosani as a recipe maintainer?  We haven't seen any activity from the existing maintainers and @fdosani is one of the project maintainers.

**Pull request merged**
