### PR TITLE
updated feedstock to version 0.7.0

### PR DESCRIPTION
**Pull request by fdosani**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

Adding version 0.7.0 to feedstock.

### CODE REVIEW

**Comment by fdosani** [comment]
Hey @conda-forge/help-python Could someone help me out with merging this PR? I'm on the maintainer list but can't seem to access any PRs to approve or merge. Thank you!

**Comment by fdosani** [comment]
@gforsyth I can't seem to ping the admins or action the repo even after being added. Would you be able to help here?

**Comment by gforsyth** [comment]
@conda-forge/help-python -- sorry for the extra pings, but @fdosani is on the recipe maintainers list but doesn't appear to have write access to this feedstock.

**Comment by beckermr** [comment]
@fdosani you need to accept the invite to conda-forge

**Comment by beckermr** [comment]
The recipe had a spacing issue which fooled one of our bots.

**Comment by fdosani** [comment]
> @fdosani you need to accept the invite to conda-forge

Thanks @beckermr just accepted!

**Comment by beckermr** [comment]
merge away, though see the PR made by our bots for 0.7.1

**Comment by fdosani** [comment]
> merge away, though see the PR made by our bots for 0.7.1

Thanks just wanted to backfill older versions.

**Pull request merged**
